### ISSUE TITLE
unable to run the script

### ISSUE THREAD

**Issue by BeimDeich** [corbin-hayden13/SD-Prompt-Enhancer#16]
The script does not work for me, I always get the following error:

> \extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py:269 in on_ui_tabs                       
>                                                                                                               
> 268                                                                                           
> 269        all_inputs = [name_label, section_dropdown, category_dropdown, multi                      
> 270        tag_input, custom_section, custom_category, custom_mul                      
>
> UnboundLocalError: local variable 'section_dropdown' referenced before assignment

02:06:27-613822 INFO     Python 3.10.6 on Windows
02:06:27-744487 INFO     Version: f6f1a73b Wed May 17 06:15:18 2023 -0400
02:06:28-183849 INFO     Latest published version: 527dc0eedf209f29cf9380a8d925b520cc3d4878 2023-05-18T23:46:11Z

**Comment by corbin-hayden13** [comment]
Take a look at the latest change.  I accidentally broke my main and  have fixed the issue, let me know if you're still having trouble

**Comment by BeimDeich** [comment]
Nope, did not work for me yet... here the error:

18:36:48-943033 ERROR    Module load: D:\KI\automatic\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py:
                         ImportError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\KI\automatic\modules\script_loading.py:13 in load_module                                                         │
│                                                                                                                     │
│   12 │   try:                                                                                                       │
│ > 13 │   │   module_spec.loader.exec_module(module)                                                                 │
│   14 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ D:\KI\automatic\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py:7 in <module>                           │
│                                                                                                                     │
│     6 from scripts.extra_helpers.tag_classes import LookupTree                                                      │
│ >   7 from scripts.extra_helpers.utils import randomize_prompt, arbitrary_priority, prompt_pri                      │
│     8                                                                                                               │
│                                                                                                                     │
│ D:\KI\automatic\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py:2 in <module>                          │
│                                                                                                                     │
│    1 from random import shuffle                                                                                     │
│ >  2 from pandas import Dataframe                                                                                   │
│    3                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'Dataframe' from 'pandas' (D:\KI\automatic\venv\lib\site-packages\pandas\__init__.py)

**Comment by corbin-hayden13** [comment]
Yeah, here, so I've been having version control issues for some reason today and have been doing a lot of development at the same time, meaning all of my development is being done on the main branch.  I fixed that issue and will stop developing off of main for now, let me know if you have any other issues.
