### ISSUE TITLE
callback Error in Vlad version of A1111

### ISSUE THREAD

**Issue by randykoala** [corbin-hayden13/SD-Prompt-Enhancer#26]
executing callback:
                         C:\Users\xxx\NewVlad\automatic\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py
                         ui_tabs_callback: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\xxx\NewVlad\automatic\modules\script_callbacks.py:151 in ui_tabs_callback                                │
│                                                                                                                     │
│   150 │   │   try:                                                                                                  │
│ > 151 │   │   │   res += c.callback() or []                                                                         │
│   152 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ C:\Users\xxx\NewVlad\automatic\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py:191 in on_ui_tabs      │
│                                                                                                                     │
│   190 │   │   │   all_sections = format_tag_database()                                                              │
│ > 191 │   │   │   token_list = sorted(make_token_list(all_sections))                                                │
│   192 │   │   │   ret_list = [priority_radio, pos_prompt_comp, curr_prompt_box, get_curr_promp                      │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\xxx\NewVlad\automatic\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py:27 in parse_and_add   │
│                                                                                                                     │
│   26 │                                                                                                              │
│ > 27 │   words = re.findall(r'\b\w*[a-zA-Z]\w*\b', str_to_parse)                                                    │
│   28 │   tokens = [word.strip().lower() for word in words if word.strip().lower() not in blac                       │
│                                                                                                                     │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\re.py:240 in findallexecuting callback:
                         C:\Users\simon\NewVlad\automatic\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py
                         ui_tabs_callback: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\xx\NewVlad\automatic\modules\script_callbacks.py:151 in ui_tabs_callback                                │
│                                                                                                                     │
│   150 │   │   try:                                                                                                  │
│ > 151 │   │   │   res += c.callback() or []                                                                         │
│   152 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ C:\Users\xxxNewVlad\automatic\extensions\SD-Prompt-Enhancer\scripts\sd_prompt_enhancer.py:191 in on_ui_tabs      │
│                                                                                                                     │
│   190 │   │   │   all_sections = format_tag_database()                                                              │
│ > 191 │   │   │   token_list = sorted(make_token_list(all_sections))                                                │
│   192 │   │   │   ret_list = [priority_radio, pos_prompt_comp, curr_prompt_box, get_curr_promp                      │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\xxx\NewVlad\automatic\extensions\SD-Prompt-Enhancer\scripts\extra_helpers\utils.py:27 in parse_and_add   │
│                                                                                                                     │
│   26 │                                                                                                              │
│ > 27 │   words = re.findall(r'\b\w*[a-zA-Z]\w*\b', str_to_parse)                                                    │
│   28 │   tokens = [word.strip().lower() for word in words if word.strip().lower() not in blac                       │
│                                                                                                                     │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\re.py:240 in findall

**Comment by corbin-hayden13** [comment]
Duplicate issue, working on patch
